// TODO: It would be ideal to have this generated by Tanstack Router.
// We can use the `useRouter()` hook to retrieve all of our routes...
// but there is no way to provide a unique `title` per Route.
// Follow this issue for updates:
// https://github.com/TanStack/router/discussions/1056

export const sitemap = [
  {
    route: '/',
    title: 'Home',
  },
  {
    route: '/overlap',
    title: 'Overlap',
  },
  {
    route: '/restricted',
    title: 'Restricted',
  },
  {
    route: '/replaced',
    title: 'Replaced',
  },
  {
    route: '/queued',
    title: 'Queued',
  },
  {
    route: '/cascade',
    title: 'Cascade',
  },
  {
    route: '/sequence',
    title: 'Sequence',
  },
  {
    route: '/asynchronous',
    title: 'Asynchronous',
  },
  {
    route: '/auto-suspend',
    title: 'Auto Suspend',
  },
  {
    route: '/visibility',
    title: 'Visibility',
  },
];
