// TODO: It would be ideal to have this generated by Tanstack Router.
// We can use the `useRouter()` hook to retrieve all of our routes...
// but there is no way to provide a unique `title` per Route.
// Follow this issue for updates:
// https://github.com/TanStack/router/discussions/1056

export const sitemap = [
  {
    route: '/',
    title: 'Home',
  },
  {
    route: '/conway',
    title: 'Conway',
  },
  {
    route: '/hacker-news',
    title: 'Hacker News',
  },
  {
    route: '/memory',
    title: 'Memory',
  },
  {
    route: '/tictactoe',
    title: 'Tic Tac Toe',
  },
];
